"""Initial tables

Revision ID: f346cdf236c0
Revises:
Create Date: 2025-10-29 12:18:20.471295

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f346cdf236c0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url_map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original", sa.Text(), nullable=False),
        sa.Column("short", sa.String(length=16), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("is_file", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("url_map", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_url_map_short"), ["short"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url_map", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_url_map_short"))

    op.drop_table("url_map")
    # ### end Alembic commands ###
